/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/a7NEq4QqJa7
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { DropdownMenuTrigger, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuItem, DropdownMenuContent, DropdownMenu } from "@/components/ui/dropdown-menu"
import { TabsTrigger, TabsList, TabsContent, Tabs } from "@/components/ui/tabs"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { SVGProps } from 'react';
import Image from 'next/image';

export function testing() {
  return (
    <div className="flex flex-col h-screen">
      <header className="flex h-14 items-center border-b bg-gray-100/40 px-6 dark:bg-gray-800/40">
        <Link className="flex items-center gap-2 font-semibold" href="#">
          <Package2Icon className="h-6 w-6" />
          <span className="">WeChat Robot</span>
        </Link>
        <div className="ml-auto flex gap-4">
          <Button
            className="rounded-full border border-gray-200 w-8 h-8 dark:border-gray-800 dark:border-gray-800"
            size="icon"
            variant="outline"
          >
            <BellIcon className="h-4 w-4" />
            <span className="sr-only">Toggle notifications</span>
          </Button>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button
                className="rounded-full border border-gray-200 w-8 h-8 dark:border-gray-800 dark:border-gray-800"
                size="icon"
                variant="ghost"
              >
                <Image
                    alt="Avatar"
                    className="rounded-full"
                    height={32}
                    src="/placeholder.svg"
                    objectFit="cover"
                    width={32}
                />
                <span className="sr-only">Toggle user menu</span>
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              <DropdownMenuLabel>我的账户</DropdownMenuLabel>
              <DropdownMenuSeparator />
              <DropdownMenuItem>设置</DropdownMenuItem>
              <DropdownMenuItem>支持</DropdownMenuItem>
              <DropdownMenuSeparator />
              <DropdownMenuItem>登出</DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </header>
      <main className="flex flex-1 flex-col gap-4 p-4 md:gap-8 md:p-6">
        <div className="flex items-center">
          <h1 className="font-semibold text-lg md:text-2xl">WeChat Robot 配置</h1>
        </div>
        <div className="border shadow-sm rounded-lg">
          <Tabs className="w-full" defaultValue="wechatter">
            <TabsList className="flex flex-wrap gap-2">
              <TabsTrigger value="wechatter">WeChatter</TabsTrigger>
              <TabsTrigger value="wx-bot-webhook">Wx-Bot-Webhook</TabsTrigger>
              <TabsTrigger value="admin">Admin</TabsTrigger>
              <TabsTrigger value="bot">Bot</TabsTrigger>
              <TabsTrigger value="chat">Chat</TabsTrigger>
              <TabsTrigger value="copilot-gpt4">Copilot-GPT4</TabsTrigger>
              <TabsTrigger value="github-webhook">GitHub-Webhook</TabsTrigger>
              <TabsTrigger value="message-forwarding">Message-Forwarding</TabsTrigger>
            </TabsList>
            <TabsContent value="wechatter">
              <div className="grid gap-4 py-4">
                <div>
                  <Label className="font-semibold">WeChatter</Label>
                  <p className="text-sm text-gray-500 dark:text-gray-400">在此处输入您的 WeChatter 信息。</p>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="wechatter-port">端口</Label>
                    <Input id="wechatter-port" placeholder="400" required />
                  </div>
                </div>
              </div>
            </TabsContent>
            <TabsContent value="wx-bot-webhook">
              <div className="grid gap-4 py-4">
                <div>
                  <Label className="font-semibold">Wx-Bot-Webhook</Label>
                  <p className="text-sm text-gray-500 dark:text-gray-400">在此处输入您的 Wx-Bot-Webhook 信息。</p>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="wx-webhook-port">端口</Label>
                    <Input id="wx-webhook-port" placeholder="3001" required />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="wx-webhook-recv-api-path">API 路径</Label>
                    <Input id="wx-webhook-recv-api-path" placeholder="/receive_msg" required />
                  </div>
                </div>
              </div>
            </TabsContent>
            <TabsContent value="admin">
              <div className="grid gap-4 py-4">
                <div>
                  <Label className="font-semibold">Admin</Label>
                  <p className="text-sm text-gray-500 dark:text-gray-400">在此处输入您的 Admin 信息。</p>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="admin-list">管理员列表</Label>
                    <Input
                      id="admin-list"
                      placeholder="&quot;[&quot;文件传输助手&quot;, &quot;皓皓&quot;, &quot;缘&quot;]&quot;"
                      required
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="admin-group-list">管理员群组列表</Label>
                    <Input id="admin-group-list" placeholder="&quot;[&quot;WeChatter&quot;]&quot;" required />
                  </div>
                </div>
              </div>
            </TabsContent>
            <TabsContent value="bot">
              <div className="grid gap-4 py-4">
                <div>
                  <Label className="font-semibold">Bot</Label>
                  <p className="text-sm text-gray-500 dark:text-gray-400">在此处输入您的 Bot 信息。</p>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="bot-name">名称</Label>
                    <Input id="bot-name" placeholder="Jerryesttt" required />
                  </div>
                </div>
              </div>
            </TabsContent>
            <TabsContent value="chat">
              <div className="grid gap-4 py-4">
                <div>
                  <Label className="font-semibold">Chat</Label>
                  <p className="text-sm text-gray-500 dark:text-gray-400">在此处输入您的 Chat 信息。</p>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="command-prefix">命令前缀</Label>
                    <Input id="command-prefix" placeholder="/" required />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="need-mentioned">需要提及</Label>
                    <Input id="need-mentioned" placeholder="False" required />
                  </div>
                </div>
              </div>
            </TabsContent>
            <TabsContent value="copilot-gpt4">
              <div className="grid gap-4 py-4">
                <div>
                  <Label className="font-semibold">Copilot-GPT4</Label>
                  <p className="text-sm text-gray-500 dark:text-gray-400">在此处输入您的 Copilot-GPT4 信息。</p>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="cp-gpt4-api-host">API 主机</Label>
                    <Input id="cp-gpt4-api-host" placeholder="http://localhost" required />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="cp-gpt4-port">端口</Label>
                    <Input id="cp-gpt4-port" placeholder="8080" required />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="cp-token">令牌</Label>
                    <Input id="cp-token" placeholder="ghu_" required />
                  </div>
                </div>
              </div>
            </TabsContent>
            <TabsContent value="github-webhook">
              <div className="grid gap-4 py-4">
                <div>
                  <Label className="font-semibold">GitHub-Webhook</Label>
                  <p className="text-sm text-gray-500 dark:text-gray-400">在此处输入您的 GitHub-Webhook 信息。</p>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="github-webhook-enabled">启用 GitHub Webhook</Label>
                    <Input id="github-webhook-enabled" placeholder="True" required />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="github-webhook-api-path">API 路径</Label>
                    <Input id="github-webhook-api-path" placeholder="/webhook/github" required />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="github-webhook-receiver-list">接收者列表</Label>
                    <Input
                      id="github-webhook-receiver-list"
                      placeholder="&quot;[&quot;文件传输助手&quot;, &quot;皓皓&quot;, &quot;缘&quot;]&quot;"
                      required
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="github-webhook-receive-group-list">接收群组列表</Label>
                    <Input
                      id="github-webhook-receive-group-list"
                      placeholder="&quot;[&quot;WeChatter&quot;]&quot;"
                      required
                    />
                  </div>
                </div>
              </div>
            </TabsContent>
            <TabsContent value="message-forwarding">
              <div className="grid gap-4 py-4">
                <div>
                  <Label className="font-semibold">Message-Forwarding</Label>
                  <p className="text-sm text-gray-500 dark:text-gray-400">在此处输入您的 Message-Forwarding 信息。</p>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="message-forwarding-enabled">启用消息转发</Label>
                    <Input id="message-forwarding-enabled" placeholder="True" required />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="message-forwarding-rules">消息转发规则</Label>
                    <Input
                      id="message-forwarding-rules"
                      placeholder="&quot;[{&quot;froms&quot;: [&quot;· C ·&quot;, &quot;🌌&quot;, &quot;无敌呆比熊&quot;, &quot;🎉花火💥&quot;, &quot;小懿同学&quot;, &quot;缘&quot;, &quot;1&quot;, &quot;Cassius&quot;],&quot;to_persons&quot;: [&quot;皓皓&quot;],&quot;to_groups&quot;: []}]&quot;"
                      required
                    />
                  </div>
                </div>
              </div>
            </TabsContent>
          </Tabs>
        </div>
      </main>
    </div>
  )
}


function Package2Icon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 9h18v10a2 2 0 1-2 2H5a2 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 1 7.24 3h9.52a2 1.8 1.1L21" />
      <path d="M12 3v6" />
    </svg>
  )
}


function BellIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 8a6 6 0 1 12 0c0 7 3 9 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 3.4" />
    </svg>
  )
}
